name: Build within Zephyr

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ main, "develop" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        app: [app]
        board: [stm32_min_dev@blue]
    env:
      CPM_SOURCE_CACHE: ${{ github.workspace }}/.cpmcache
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ matrix.app }}

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: ${{ matrix.app }}
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: ${{ matrix.app }}
        shell: bash
        run: |
          west build -b ${{ matrix.board }} -d ${{ matrix.app }}/build --sysbuild ${{ matrix.app }}

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}
          path: |
            ${{ matrix.app }}/build/${{ matrix.app }}/zephyr/merged.hex
            ${{ matrix.app }}/build/${{ matrix.app }}/zephyr/zephyr.elf
            ${{ matrix.app }}/build/bootloader/bluepill-can-bl.elf
